[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "solidauth-oidc"
version = "0.1.0"
description = "Solid OIDC client for Python"
readme = "README.md"
requires-python = ">=3.11"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
    { name = "Music Technology Group, Universitat Pompeu Fabra" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "jwcrypto~=1.5.8",
    "oic>=1.7.0",
    "rdflib~=7.1.4",
    "requests~=2.34.2",
    "sqlalchemy~=2.0.51",
]

[project.urls]
Repository = "https://github.com/trompamusic/solidauth-oidc"

[tool.setuptools.packages.find]
include = ["solidauth*"]
exclude = ["solidauth.tests*"]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
ignore = ["E741"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
demo = [
    "click~=8.4.2",
    "flask[dotenv]~=3.1.3",
    "flask-admin[sqlalchemy]~=2.2.0",
    "flask-bcrypt~=1.0.1",
    "flask-login~=0.6.3",
    "flask-shell-ipython~=0.5.3",
    "flask-sqlalchemy~=3.1.1",
    "flask-wtf~=1.3.0",
    "psycopg2-binary~=2.9.12",
    "wtforms~=3.2.2",
]

[tool.uv]
default-groups = ["dev", "demo"]
